name: Build and Release FFastGPU

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Set version environment variables
        run: |
          echo "VERSION=0.0.0.3" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
          echo "RELEASE_TAG=v0.0.0.3" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append

      - name: Build executable
        run: cmd /c build.bat

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: FFastGPU-exe
          path: dist/FFastGPU.exe

      - name: Create GitHub Release (draft)
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ env.RELEASE_TAG }}
          name: ${{ env.RELEASE_TAG }}
          draft: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Release Asset
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ env.RELEASE_TAG }}
          files: dist/FFastGPU.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}