name: Build and Release FFastGPU

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Needed to push tags back

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install pyinstaller

      - name: Increment version
        id: version
        run: |
          python increment_version.py
          echo "VERSION=$(python -c 'from version import VERSION; print(VERSION)')" >> $GITHUB_ENV

      - name: Tag commit
        if: github.ref == 'refs/heads/main'
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git tag -a "v$VERSION" -m "Auto-tag version $VERSION"
          git push origin "v$VERSION"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Build executable
        run: cmd /c build.bat

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: FFastGPU-exe
          path: dist/FFastGPU.exe

      - name: Create GitHub Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref_name }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Release Asset
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1
        with:
          files: dist/FFastGPU.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
