name: Build FFastGPU

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install pyinstaller

      - name: Build executable
        run: |
          python increment_version.py
          pyinstaller --clean --onefile --windowed `
            --name "FFastGPU" `
            --version-file version_info.txt `
            FFastGPU.py

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: FFastGPU-exe
          path: dist/FFastGPU.exe
